# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PortX.ptx
PackageVersion: 1.0.22
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ptx.exe
  PortableCommandAlias: ptx
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/portx-labs/ptx-cli/releases/download/v1.0.22/ptx-cli-windows-amd64.zip
  InstallerSha256: FF23AD87BCEDCD56439C5C55606F8BDEE9DB3EF638FA53BEEA96A63AB623D3B4
- Architecture: arm64
  InstallerUrl: https://github.com/portx-labs/ptx-cli/releases/download/v1.0.22/ptx-cli-windows-arm64.zip
  InstallerSha256: 60324124F8E05B3FC63EBE59C4B16F1FC1CD5712CE8A08002B80ADAAAC3246AD
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-13
